export enum HTTP_RESPONSE {
    OK = 200,
    CREATED = 201,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    INTERNAL_ERROR = 500,
    NOT_FOUND = 404
}

export enum VALIDATOR_MESSAGES {
    IS_REQUIRED = 'LA PROPIEDAD $ ES REQUERIDA',
    NOT_ALLOWED = 'LA PROPIEDAD $ NO ES PERMITIDA',
    NEED_VERIFED = 'VERIFIQUE LA PROPIEDAD $',
    WRONG_TYPE = 'LA PROPIEDAD $ DEBE SER DE TIPO ?',
    WRONG_MIN_SIZE = 'LA PROPIEDAD $ DEBER TENER UN TAMAÑO MINIMO DE ?',
    WRONG_MAX_SIZE = 'LA PROPIEDAD $ DEBER TENER UN TAMAÑO MAXIMO DE ?'
}

export enum RESPONSE_API_MESSAGES {
    VALIDATE_ERROR = 'ERROR AL VALIDAR INFORMACION'
}
